# German Language File

# User Commands

slot:

  new_user:
    user:  'Willkommen im Rudel,\n
            du bekommst diese kurze Nachricht hier, weil du dich für ein {}-Event anmelden wolltest, ohne das du unseren kleinen Technik-Check absolviert hast. Der ist gar nicht so unwichtig! Wir führen ihn im Moment auf
            wöchentlicher Basis durch oder nach Absprache. Du erfährst da ein paar nette Details, die dir am Anfang weiterhelfen und wie du möglichst ohne technische Probleme hier mitmachen kannst.\n
            Schreib doch bitte **{}** an, das ist unser {}-Einstiegshelfer-Team.\n\n
            Wir machen das im Sinne der Gemeinschaft und damit jeder ein möglichst angenehmes Spielerlebnis hat. Und damit für die Zukunft noch ein: viel Spaß!'

    channel: "{} ({}) hat versucht sich für das Event {} in der Position #{} einzutragen"
    instructor: "{} ({}) hat versucht sich für das Event {} in der Position #{} einzutragen"

  slot:
    success:
      channel_author: "{} ({}) hat sich für das Event {} in der Position #{} eingetragen"
      user: "Du hast dich für das Event am {} eingetragen."

    error:
      taken:
        channel: "Der angegebene Slot ist schon vergeben!"
      invalid:
        channel: "Der angegebene Slot ist ungültig!"
      locked:
        channel: "Die Slotliste ist gesperrt!"
      number_missing:
        channel: "Bitte gib einen Slot an!"

unslot:

  success:
    channel_author: "{} ({}) hat sich für das Event {} aus der Position #{} {}**ausgetragen**{}"
    user : "Du hast dich für das Event am {} ausgetragen."

  error:
    general:
      channel: "Du kannst dich nicht austragen, wenn du nicht in der Liste eingetragen bist"

mark:
  suc: "Die Markierung wurde erfolgreich hinzugefügt."
  error:
    typeNotFound: "Die Art der Markierung wurde nicht gefunden."
    duplicate: "Du hast bereits diese Art der Markierung für dieses Event ausgewählt."
    args: "Du musst eine Markierung angeben, welche du dir für dieses Event geben möchtest."

unmark:
  suc: "Die Markierung wurde erfolgreich entfernt."
  error:
    typeNotFound: "Die Art der Markierung wurde nicht gefunden."
    duplicate: "Du hast diese Art der Markierung nicht."
    args: "Du musst eine Markierung angeben, welche du dir für dieses Event geben möchtest."


trade:
  request: "{} möchte mit Dir ({}) seinen Slot ({}) für das Event {} tauschen. Du kannst dies in den nächsten 24h mittels
            Reaktion bestätigen oder ablehnen. Bei Ablauf der Frist, wird die Anfrage automatisch abgelehnt."

  private:
    timeout:
      rec: "Die Zeit für die Anfrage von {} für das Event {} ist abgelaufen."
      req: "Die Zeit für die Anfrage an {} für das Event {} ist abgelaufen."

    accept:
      rec: "Du hast den Slot mit {} in dem Event {} getauscht."
      req: "{} hat deinem Tauschangebot für das Event {} zugestimmt."
      backup: "{} hat mit {} im Event {} getauscht"
      error: "Ein Fehler ist aufgetreten. Bitte wende dich an [RR] Wasserstoff."

    unslot: "{} ist nicht mehr angemeldet!"

    deny:
      rec: "Du hast das Tauschangebot von {} für das Event {} abgelehnt."
      req: "{} hat das Tauschangebot für das Event {} abgelehnt."
      error: "Ein Fehler ist aufgetreten. Bitte wende dich an [RR] Wasserstoff."

  channel:
    error:
      arg: "Bitte gib einen gültigen Nutzer an!"
      val: "Bitte git einen gültigen Nutzer an, welcher auch in der Slotliste eingetragen ist! \n
            Du darfst dich nicht in der Reserve befinden."
      limit: "Du hast bereits für das Event eine Anfrage gestellt!"
      send: "Ein Fehler ist aufgetreten, bitte wende dich an [RR] Wasserstoff!"

    success: "Du hast erfolgreich ein Tauschangebot abgeschickt."

notify_global:
    toggle:
      private: "Du wirst nun {} benachrichtigt (Global)."
      channel:
        suc: "Die Änderung war Erfolgreich."
        fail: "Du musst dich schon einmal für Event eingetragen haben, um eine Änderung durchzuführen."
    noti: "Hey {},\n nicht vergessen: Im Rudel ist das Event {} um {}. Rechner in Form bringen, Getränke bereitstellen und gute Laune einpacken :D"

notify_local:
    toggle:
      private: "Du wirst nun {} für das Event {} benachrichtigt."
      channel:
        suc: "Die Änderung war Erfolgreich."
        fail: "Du musst dich für das Event eingetragen haben, um eine Änderung durchzuführen."

    time:
      private: "Du wirst für das Event {} nun am {} benachrichtigt."
      channel:
        suc: "Die Änderung war Erfolgreich."
        dig: "Die Zeit in [h] muss ganzzahlig angegeben werden!"
        large: "Die Zahl ist zu groß."
        fail: "Du musst dich für das Event eingetragen haben, um eine Änderung durchzuführen."



# -------------------------------------------------------------------
# Admin Commands

create:
  success:
    user: "Das Event wurde erfolgreich erstellt"
  error:
    general:
      user: "Die Slotliste wurde nicht erkannt!\n
      Slotlisten müssen mit `>Slotliste<` gekenntzeichnet sein!"
    time:
      user: "Es wurde kein Eventstart gefunden. Bitte gib diesen im Channel an mit der Syntax: \n
      `Eventstart: [Uhrzeit]` \n im Format hh:mm"

update:
  auto:
    success: "Das Datum von {} wurde geändert!"
    date_error: "Das Datum von {} wurde nicht geändert! Das Datum (im Discord) ist ungültig."
    error: "Das Datum von {} wurde nicht geändert!"
  command:
    success: "Das Datum und der Evenstart von {} wurde geändert!"
    broadcast: "Die Uhrzeit und/oder das Datum des Events <#{}> um {} wurden verändert."
    date_error: "Das Event {} wurde nicht geändert! Das Datum (im Discord) ist ungültig."
    time_error: "Das Event {} wurde nicht geändert! Die Eventzeit (im Discord) ist ungültig."
    error: "Das Event {} wurde nicht geändert!"


lock:
  toggle:
    success: "Die Sperrung wurde umgeschalten."
    error: "Die Sperrung konnte nicht umgeschalten werden."
  slotlist: "Gesperrt"

campaign:
  request:
    message: "{} macht Dir ein Angebot was Du nicht ablehnen kannst. Möchtest Du beim nächsten Teil seiner Kampagne am
              {} als {} auf dem Slot {} wieder mitspielen? Bestätige dies bitte innerhalb der nächsten 2 Tage mittels Reaktion,
              ansonsten steht der Slot wieder zur freien Verfügung."
    error:
      user: "Ein Fehler ist aufgetreten, bitte wende dich an den Missionsbauer oder [RR] Wasserstoff"
      admin: "Die Kampangen-Nachricht beim Nutzer {} wurde nicht erstellt!"
  channel:
    success: "Die Anfragen wurden erfolgreich generiert"
    error: "Es liegt ein Fehler vor; ist der Event-Name bzw. die Event-ID korrekt?"
    not_event: "In diesem Kanal gibt es noch keine initialisierte Slotliste!"
  private:
    accept:
      success: "Du hast dich erfolgreich zurückgemeldet"
      error: "Ein Fehler ist aufgetreten, bitte wende dich an den Missionsbauer oder [RR] Wasserstoff"
    deny:
        success: "Du hast dich erfolgreich ausgetragen"
        error: "Ein Fehler ist aufgetreten, bitte wende dich an den Missionsbauer oder [RR] Wasserstoff"
    timeout: "Da die Zeit abgelaufen ist, wurdest Du nun automatisch ausgetragen"

forceSlot:
  success:
    channel: "Der User wurde eingetragen!"
    target: "Du wurdest von {} zum Event am {} eingetragen"

  error:
    general:
      channel: "Der angegebene Slot ist ungültig!"
    arg_error:
      channel: "Bitte gib einen **Slot** und **User** an!"
    missing_target:
      channel: "Bitte gib einen gültigen **User** an!"

forceUnslot:

  success:
    channel: "{} wurde entfernt!"
    target: "Du wurdest von dem Event {} ausgetragen"

  error:
    general:
      channel: "{} ist nicht eingetragen!"
    missing_target:
      channel: "Bitte gib Argumente an!"
    missing_slot:
      channel: "Bitte gib einen **Slot** an!"
addslot:

  success:
    channel: "Der Slot wurde erfolgreich hinzugefügt!"

  error:
    general:
      channel: "Der angegebne Slot ist ungültig"
    arg_error:
      channel: "Bitte gib einen gültigen **Slot** mit **Beschreibung** an!"

delslot:

  success:
    channel: "Der angegebene Slot wurde entfernt!"
  error:
    general:
      channel: "Der angegebene Slot ist ungültig!"

editslot:

  success:
    channel: "Der Slot wurde erfolgreich bearbeitet!"

  error:
    general:
      channel: "Der angegebne Slot ist ungültig"
    arg_error:
      channel: "Bitte gib einen gültigen **Slot** mit **Beschreibung** an!"

addgroup:

  success:
    channel: "Die Gruppe wurde erfolgreich hinzugefügt!"

  error:
    general:
      channel: "Die angegebene Gruppe ist ungültig"
    arg_error:
      channel: "Bitte gib eine gültige Gruppe an!"

delgroup:

  success:
    channel: "Die Gruppe wurde erfolgreich gelöscht!"

  error:
    general:
      channel: "Die angegebene Gruppe ist ungültig"
    arg_error:
      channel: "Bitte gib eine gültige Gruppe an!"

editgroup:

  success:
    channel: "Der Gruppenname wurde erfolgreich geändert!"

  error:
    general:
      channel: "Die angegebene Gruppe ist ungültig"
    arg_error:
      channel: "Bitte gib eine gültige Gruppe an!"
